on: [pull_request, push]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: '27'
        rebar3-version: '3.24.0'
    - run: rebar3 eunit
